
auth_key_user: ubuntu

head_nodes: "{{ groups['dev_slurm_head'] }}"
worker_nodes: "{{ groups['dev_workers'] }}"
galaxy_nodes: "{{ groups['dev_galaxy_server'] }}"

add_galaxy_user: true #Adds the galaxy user to all machines that have slurm on them 

# SLURM
slurm_nodes:
    - name: dev-w1
      NodeAddr: 115.146.85.210
      CPUs: 4
      RealMemory: 7780
      State: UNKNOWN
    - name: dev-queue
      NodeAddr: 115.146.85.163
      CPUs: 2
      RealMemory: 3300
      State: UNKNOWN
    - name: dev
      NodeAddr: 115.146.86.50
      CPUs: 4
      RealMemory: 7780
      State: UNKNOWN

slurm_partitions:
    - name: main
      nodes: "dev-w1"
      Default: YES
      MaxTime: '30-00:00:00'
      State: UP

slurm_config:
    #SlurmDBd includes
    AccountingStorageType: accounting_storage/slurmdbd
    AccountingStorageHost: localhost
    JobAcctGatherType: jobacct_gather/linux
    ControlMachine: dev-queue
    SlurmctldPidFile: /run/slurmctld.pid
    SlurmdPidFile: /run/slurmd.pid
    # SCHEDULING
    FastSchedule: 2
    SchedulerType: sched/backfill
    SelectType: select/cons_res
    SelectTypeParameters: CR_CPU,CR_LLN

slurm_munge_key: files/keys/munge.key
