
auth_key_user: ubuntu

# SLURM
slurm_nodes:
    - name: dev-pulsar
      NodeAddr: "{{ hostvars['dev-pulsar']['ansible_ssh_host'] }}"
      CPUs: 2
      RealMemory: 7950
      State: UNKNOWN

slurm_partitions:
    - name: main
      nodes: "dev-pulsar"
      Default: YES
      MaxTime: '30-00:00:00'
      State: UP

slurm_controller_host: dev-pulsar

slurm_munge_key: files/keys/munge.key
