slurm_roles: ['exec']

add_hosts_head: yes
add_hosts_galaxy: yes

shared_mounts:
    - path: /mnt/galaxy
      src: dev:/mnt/galaxy
      fstype: nfs
      state: mounted

#CVMFS
cvmfs_role: client
galaxy_cvmfs_repos_enabled: true
