slurm_roles: ['exec']

add_hosts_head: yes
add_hosts_galaxy: yes

shared_mounts:
    - path: /mnt/galaxy
      src: dev:/mnt/galaxy
      fstype: nfs
      state: mounted

# Interactive Tools
docker_install_compose: false
docker_users:
  - "{{ galaxy_user.name }}"