
auth_key_user: ubuntu

# SLURM
slurm_nodes:
    - name: staging-pulsar
      NodeAddr: "{{ hostvars['staging-pulsar']['ansible_ssh_host'] }}"
      CPUs: 4
      RealMemory: 7780
      State: UNKNOWN

slurm_partitions:
    - name: main
      nodes: "staging-pulsar"
      Default: YES
      MaxTime: '30-00:00:00'
      State: UP

slurm_controller_host: staging-pulsar

slurm_munge_key: files/keys/munge.key
