
auth_key_user: ubuntu

head_nodes: "{{ groups['staging_slurm_head'] }}"
worker_nodes: "{{ groups['staging_workers'] }}"
galaxy_nodes: "{{ groups['staging_galaxy_server'] }}"

add_galaxy_user: true #Adds the galaxy user to all machines that have slurm on them

# SLURM
slurm_nodes:
    - name: staging-w1
      NodeAddr: "{{ hostvars['staging-w1']['ansible_ssh_host'] }}"
      CPUs: 4
      RealMemory: 15580
      State: UNKNOWN
    - name: staging-queue
      NodeAddr: "{{ hostvars['staging-queue']['ansible_ssh_host'] }}"
      CPUs: 2
      RealMemory: 3300
      State: UNKNOWN
    - name: staging
      NodeAddr: "{{ hostvars['staging']['ansible_ssh_host'] }}"
      CPUs: 4
      RealMemory: 7780
      State: UNKNOWN

slurm_partitions:
    - name: main
      nodes: "staging-w1"
      Default: YES
      MaxTime: '30-00:00:00'
      State: UP

slurm_controller_host: staging-queue

slurm_munge_key: files/keys/munge.key
