- hosts: dev_workers
  become: true
  vars_files:
      - group_vars/all.yml
      - group_vars/dev.yml
      - group_vars/VAULT
      - group_vars/dev_slurm.yml
      - group_vars/dev_workers.yml
  roles:
      - common
      - insspb.hostname
      - geerlingguy.pip
      - mounts
      - galaxyproject.repos
      - galaxyproject.slurm
      - galaxyproject.cvmfs
  post_tasks:
      - name: restart munge
        systemd:
            name: munge
            state: restarted
