- hosts: pawsey_galaxy_server
  become: true
  vars_files:
      - group_vars/all.yml
      - group_vars/pawsey.yml
      - group_vars/VAULT
      - group_vars/galaxyservers.yml
      - group_vars/pawsey_slurm.yml
      - host_vars/pawsey.usegalaxy.org.au.yml
      - host_vars/pawsey_job_conf.yml
  handlers:
    - name: Restart Galaxy
      systemd:
        name: galaxy
        state: restarted
  tasks:
    - name: copy new job_conf file
      template:
        src: "{{ galaxy_config_template_src_dir }}/config/job_conf.xml.j2"
        dest: "{{ galaxy_config_dir}}/job_conf.xml"
      notify: Restart Galaxy
