- hosts: pulsar-mel3
  become: true
  vars_files:
    - group_vars/all.yml
    - group_vars/pulsar_mel3/pulsar-mel3.yml
    - group_vars/pulsarservers.yml
    - group_vars/pulsar_mel3/pulsar-mel3_slurm.yml
    - group_vars/VAULT
    - host_vars/pulsar-mel3/pulsar-mel3.genome.edu.au.yml
  roles:
    - common
    - insspb.hostname
    - geerlingguy.pip
    - galaxyproject.repos
    - galaxyproject.pulsar
    - geerlingguy.nfs
    - mariadb
    - galaxyproject.slurm
    - galaxyproject.cvmfs
    - dj-wasabi.telegraf

  post_tasks:
    - name: Install slurm-drmaa
      package:
        name: slurm-drmaa1
        state: present
    - name: own the /mnt/pulsar dirs as ubuntu
      file:
          path: /mnt/pulsar
          owner: ubuntu
          group: ubuntu
          state: directory
          recurse: yes
          mode: 0750
    - name: own the /mnt/galaxy dirs as ubuntu
      file:
          path: /mnt/galaxy
          owner: ubuntu
          group: ubuntu
          state: directory
          recurse: yes
          mode: 0750
