- name: Pulsar mel3 worker node install
  hosts: pulsar-mel3-workers
  become: yes
  vars_files:
    - group_vars/all.yml
    - group_vars/pulsar_mel3/pulsar-mel3.yml
    - group_vars/pulsar_mel3/pulsar-mel3_workers.yml
    - group_vars/pulsar_mel3/pulsar-mel3_slurm.yml
    - group_vars/VAULT
  roles:
      - common
      - insspb.hostname
      - galaxyproject.slurm
      - mounts
      - galaxyproject.repos
      - galaxyproject.cvmfs
      - dj-wasabi.telegraf
  post_tasks:
      - name: Restart munge service
        service:
            name: munge
            state: restarted