- hosts: pulsar-mel2
  become: true
  vars_files:
    - group_vars/all.yml
    - group_vars/pulsar_mel2/pulsar-mel2.yml
    - group_vars/pulsarservers.yml
    - group_vars/pulsar_mel2/pulsar-mel2_slurm.yml
    - group_vars/VAULT
    - host_vars/pulsar-mel2/pulsar-mel2.genome.edu.au.yml
    - secret_group_vars/stats_server_vault
    - secret_group_vars/ubuntu_maintenance_key
  pre_tasks:
    - name: apt update
      apt:
        cache_valid_time: 3600
        update_cache: yes
      when: ansible_os_family == "Debian"
    # attached_volumes role is broken for legacy cases where there is no partition set.
    # If we need to run this role again we should be adding partition to each attached_volumes entry for this VM
    # - name: Attach volume to instance If we need to run this role again we should add parition to the attached_volumes entries for this VM
    #   include_role:
    #     name: attached-volumes
    - name: Create pulsar deps path
      file:
        path: "{{ pulsar_dependencies_dir }}"
        state: directory
        owner: "{{ pulsar_user.name }}"
        group: "{{ pulsar_user.name }}"
  roles:
    - common
    - insspb.hostname
    - geerlingguy.pip
    - galaxyproject.repos
    - role: galaxyproject.miniconda
      become: true
      become_user: "{{ pulsar_user.name }}"
    - galaxyproject.pulsar
    - geerlingguy.nfs
    - mariadb
    - galaxyproject.slurm
    - galaxyproject.cvmfs
    - gantsign.golang
    - cyverse-ansible.singularity
    - geerlingguy.docker
    - acl-on-startup
    - dj-wasabi.telegraf
    - pulsar-post-tasks
    - slurm-post-tasks
    - slg.galaxy_stats
  post_tasks:
    - name: Reload exportfs
      command: exportfs -ra
