- hosts: staging_galaxy_server
  become: true
  vars_files:
      - group_vars/all.yml
      - group_vars/staging.yml
      - group_vars/VAULT
      - group_vars/galaxyservers.yml
      - group_vars/staging_slurm.yml
      - host_vars/staging.usegalaxy.org.au.yml
      - secret_group_vars/ubuntu_maintenance_key
  handlers:
    - name: restart handlers
      become: True
      become_user: galaxy
      command: "{{ galaxy_venv_dir }}/bin/galaxyctl restart handler_0 handler_1 handler_2"
      environment:
        GRAVITY_STATE_DIR: "{{ galaxy_gravity_state_dir }}"
  pre_tasks:
    - name: copy job_conf file
      template:
        src: "{{ galaxy_config_template_src_dir }}/config/staging_job_conf.yml.j2"
        dest: "{{ galaxy_config_dir }}/job_conf.yml"
      notify: restart handlers
    - name: Install dynamic job rules (static) # dynamic job rules tasks copied from https://github.com/galaxyproject/ansible-galaxy/blob/main/tasks/static_setup.yml
      copy:
        src: "{{ galaxy_dynamic_job_rules_src_dir }}/{{ item }}"
        dest: "{{ galaxy_dynamic_job_rules_dir }}/{{ item }}"
        mode: 0644
      with_items: "{{ galaxy_dynamic_job_rules }}"
      when: not item.endswith(".j2")
    - name: Install dynamic job rules (template)
      template:
        src: "{{ galaxy_dynamic_job_rules_src_dir }}/{{ item }}"
        dest: "{{ galaxy_dynamic_job_rules_dir }}/{{ item | regex_replace(regex) }}"
        mode: 0644
      vars:
        regex: '\.j2$'
      with_items: "{{ galaxy_dynamic_job_rules }}"
      when: item.endswith(".j2")
