name: Proteomics toolbox
id: proteomics
type: activity
items:
- type: label
  text: Proteomics
- type: section
  id: proteomics
  name: Proteomics
  items:
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/iracooke/mascot/proteomics_search_mascot_1
- type: section
  id: dia
  name: DIA
  items:
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/galaxyp/encyclopedia_encyclopedia/encyclopedia_encyclopedia
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/galaxyp/encyclopedia_quantify/encyclopedia_quantify
