name: Proteomics Panel Filter
type: generic
items:
- type: label
  text: Proteomics
- type: section
  id: databases
  name: Databases
  items:
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/galaxyp/custom_pro_db/custom_pro_db
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_decoydatabase/DecoyDatabase
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_falsediscoveryrate/FalseDiscoveryRate
- type: section
  id: dia
  name: DIA
  items:
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/galaxyp/dia_umpire/dia_umpire_se
  - type: tool
    id: toolshed.g2.bx.psu.edu/repos/galaxyp/diann/diann
    