name: Proteomics toolbox
id: proteomics
type: activity
items:
- type: label
  text: Proteomics
- type: section
  id: databases
  name: Databases
  items:
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/custom_pro_db/custom_pro_db
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_decoydatabase/DecoyDatabase
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_falsediscoveryrate/FalseDiscoveryRate
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/peptideshaker/fasta_cli
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/uniprotxml_downloader/uniprotxml_downloader
- type: section
  id: dia
  name: DIA
  items:
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/dia_umpire/dia_umpire_se
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/diann/diann
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/diapysef/diapysef
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/encyclopedia_encyclopedia/encyclopedia_encyclopedia
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/encyclopedia_quantify/encyclopedia_quantify
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/encyclopedia_searchtolib/encyclopedia_searchtolib
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/encyclopedia_walnut/encyclopedia_walnut
- type: section
  id: feature_identification
  name: Feature identification
  items:
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/proteomics_moff/proteomics_moff
- type: section
  id: file_conversion
  name: File conversion
  items:
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/msconvert/msconvert
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/iracooke/tpp_prophets/pepxml_to_table_1
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/iracooke/tpp_prophets/protxml_to_table_1
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/percolator/percolator_input_converters
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/iracooke/xtandem/tandem_to_pepxml_1
- type: section
  id: file_modification
  name: File modification
  items:
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/percolator/batched_set_list_creator
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/percolator/pout2mzid
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/pyprophet_merge/pyprophet_merge
- type: section
  id: genomics_classification
  name: Genomics classification
  items:
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/pep_pointer/pep_pointer
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/peptide_genomic_coordinate/peptide_genomic_coordinate
- type: section
  id: identification_quantitation
  name: Identification and quantitation
  items:
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/flashlfq/flashlfq
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/maxquant/maxquant
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/maxquant/maxquant_mqpar
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/maxquant_mqpar/maxquant_mqpar
- type: section
  id: metaquantome
  name: metaQuantome
  items:
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/metaquantome_sample/metaquantome_sample
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/metaquantome_db/metaquantome_db
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/metaquantome_expand/metaquantome_expand
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/metaquantome_filter/metaquantome_filter
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/metaquantome_stat/metaquantome_stat
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/metaquantome_viz/metaquantome_viz
- type: section
  id: msi
  name: MSI
  items:
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/maldi_quant_peak_detection/maldi_quant_peak_detection
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/maldi_quant_preprocessing/maldi_quant_preprocessing
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/cardinal_classification/cardinal_classification
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/cardinal_combine/cardinal_combine
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/cardinal_data_exporter/cardinal_data_exporter
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/cardinal_filtering/cardinal_filtering
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/cardinal_mz_images/cardinal_mz_images
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/cardinal_spectra_plots/cardinal_spectra_plots
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/cardinal_preprocessing/cardinal_preprocessing
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/cardinal_quality_report/cardinal_quality_report
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/cardinal_segmentations/cardinal_segmentations
- type: section
  id: openms
  name: OpenMS
  items:
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_consensusid/ConsensusID
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_featurefindermultiplex/FeatureFinderMultiplex
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_fidoadapter/FidoAdapter
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_fileconverter/FileConverter
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_filefilter/FileFilter
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_fileinfo/FileInfo
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_filemerger/FileMerger
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_highresprecursormasscorrector/HighResPrecursorMassCorrector
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_idconflictresolver/IDConflictResolver
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_idfilter/IDFilter
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_idmapper/IDMapper
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_idmerger/IDMerger
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_idposteriorerrorprobability/IDPosteriorErrorProbability
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_idscoreswitcher/IDScoreSwitcher
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_msfraggeradapter/MSFraggerAdapter
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_msgfplusadapter/MSGFPlusAdapter
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_multiplexresolver/MultiplexResolver
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_mztabexporter/MzTabExporter
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_openswathanalyzer/OpenSwathAnalyzer
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_openswathassaygenerator/OpenSwathAssayGenerator
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_openswathconfidencescoring/OpenSwathConfidenceScoring
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_openswathdecoygenerator/OpenSwathDecoyGenerator
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_openswathdiaprescoring/OpenSwathDIAPreScoring
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_openswathfilesplitter/OpenSwathFileSplitter
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_openswathmzmlfilecacher/OpenSwathMzMLFileCacher
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_openswathrtnormalizer/OpenSwathRTNormalizer
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_openswathworkflow/OpenSwathWorkflow
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_peakpickerhires/PeakPickerHiRes
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_peptideindexer/PeptideIndexer
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_proteinquantifier/ProteinQuantifier
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_targetedfileconverter/TargetedFileConverter
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_textexporter/TextExporter
- type: section
  id: peptide_identification
  name: Peptide identification
  items:
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/percolator/percolator
- type: section
  id: post_processing
  name: Post-processing
  items:
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/iracooke/tpp_prophets/proteomics_search_interprophet_1
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/msstats/msstats
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/msstatstmt/msstatstmt
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/iracooke/tpp_prophets/proteomics_search_peptide_prophet_1
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/iracooke/tpp_prophets/proteomics_search_protein_prophet_1
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/pyprophet_peptide/pyprophet_peptide
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/pyprophet_protein/pyprophet_protein
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/pyprophet_score/pyprophet_score
- type: section
  id: protein_identification
  name: Protein identification
  items:
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/peptideshaker/peptide_shaker
- type: section
  id: quality_control
  name: Quality control
  items:
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/rawtools/rawtools
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_xmlvalidator/XMLValidator
- type: section
  id: search_engine
  name: Search engine
  items:
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/peptideshaker/ident_params
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/morpheus/morpheus
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/peptideshaker/search_gui
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/iracooke/xtandem/proteomics_search_tandem_1
    - type: tool
      id: toolshed.g2.bx.psu.edu/repos/galaxyp/openms_xtandemadapter/XTandemAdapter
