- hosts: localhost
  tasks:
    - name: ensure directories exist in backup repo
      file:
        path: "{{ config_backup_dir }}/{{ item }}"
        state: directory
      with_items:
        - galaxy_mutable_config
        - tiaas
        - history_mailer
- hosts:
    - galaxy
  become: true
  tasks:
    - name: Copy files from /mnt/galaxy/var
      fetch:
        flat: yes
        fail_on_missing: no
        src: "/mnt/galaxy/var/{{ item }}"
        dest: "{{ config_backup_dir }}/galaxy_mutable_config/"
      with_items:
        - integrated_tool_panel.xml
        - migrated_tools_conf.xml
        - sanitize_allowlist.txt
        - shed_data_manager_conf.xml
        - shed_tool_conf.xml
        - shed_tool_data_table_conf.xml
        - galaxy_install_db.sqlite
    - name: Copy tiaas db
      fetch:
        flat: yes
        fail_on_missing: no
        src: "/opt/tiaas/{{ item }}"
        dest: "{{ config_backup_dir }}/tiaas/"
      with_items:
        - db.sqlite3
- hosts:
    - galaxy-backup
  become: true
  tasks:
    - name: Copy history mailer db
      fetch:
        flat: yes
        fail_on_missing: no
        src: "/home/ubuntu/mailer/{{ item }}"
        dest: "{{ config_backup_dir }}/history_mailer/"
      with_items:
        - prod_hm.sqlite
