
- hosts: "{{ source_galaxy }}"
  become: true
  vars_files:
    - vars.yml
    - secret_vars/tool_migration_rsync_key.yml
  vars:
    - extra_key:
        id: tool_migration_rsync_key
        type: public
        from: "{{ hostvars[dest_galaxy]['ansible_ssh_host'] }}"
  tasks:
    - name: Install keys using common role
      include_role:
        name: common
        tasks_from: extra_keys
    - name: Ensure migration directories exists on past galaxy
      file:
        path: "{{ item }}"
        state: directory
        owner: galaxy
        group: galaxy
      with_items:
        - "{{ galaxy_tool_migration_dir }}"
        - "{{ galaxy_tool_migration_dir }}/conda_envs"
    - name: Get a list of all of the environments in the envs dir
      find:
        paths:
            - "{{ source_conda_envs_dir }}"
        file_type: directory
        depth: 1
      register: conda_environments_dir_list
    - name: Now for each env, run conda env export if there is no export file
      become: true
      become_user: galaxy
      ignore_errors: true # imagine there might be one or two dirs that is not a conda environment
      command:
        cmd: "{{ source_conda_prefix }}/bin/conda env export -n {{ item }} -f {{ galaxy_tool_migration_dir }}/conda_envs/{{ item }}.yml"
        creates: "{{ galaxy_tool_migration_dir }}/conda_envs/{{ item }}.yml"
      with_items: "{{ conda_environments_dir_list.files | map(attribute='path') | map('basename') }}"

- hosts: "{{ dest_galaxy }}"
  become: true
  vars_files:
    - vars.yml
    - secret_vars/tool_migration_rsync_key.yml
  vars:
    - extra_key:
        id: tool_migration_rsync_key
        type: private
  tasks:
    - name: Ensure migration directories exists on future galaxy
      file:
        path: "{{ item }}"
        state: directory
        owner: galaxy
        group: galaxy
      with_items:
        - "{{ galaxy_tool_migration_dir }}"
        - "{{ galaxy_tool_migration_dir }}/conda_envs"
        - /home/galaxy/.ssh
    - name: Install keys using common role
      include_role:
        name: common
        tasks_from: extra_keys
    - name: template rsync script
      template:
        src: tool_migration_rsync_script.sh.j2
        dest: /home/galaxy/tool_migration_rsync_script.sh
        owner: galaxy
        group: galaxy
      vars:
        ssh_key: /home/galaxy/.ssh/tool_migration_rsync_key
        source_galaxy_ip: "{{ hostvars[source_galaxy]['ansible_ssh_host'] }}"
      
