
auth_key_user: ubuntu

head_nodes: "{{ groups['pulsar_nci_test_head'] }}"
worker_nodes: "{{ groups['pulsar_nci_test_workers'] }}"
use_internal_ips: true

# SLURM
slurm_nodes:
    - name: pulsar-nci-test
      NodeAddr: "{{ hostvars['pulsar-nci-test']['internal_ip'] }}"
      CPUs: 8
      RealMemory: 16380
      State: UNKNOWN
    - name: pulsar-nci-test-w1
      NodeAddr: "{{ hostvars['pulsar-nci-test-w1']['internal_ip'] }}"
      CPUs: 16
      RealMemory: 49350
      State: UNKNOWN
    - name: pulsar-nci-test-w2
      NodeAddr: "{{ hostvars['pulsar-nci-test-w2']['internal_ip'] }}"
      CPUs: 16
      RealMemory: 49350
      State: UNKNOWN

slurm_partitions:
    - name: main
      nodes: "pulsar-nci-test-w1,pulsar-nci-test-w2"
      Default: YES
      MaxTime: INFINITE
      State: UP

slurm_controller_host: pulsar-nci-test

slurm_munge_key: files/keys/munge.key
