slurm_roles: ['exec']

add_hosts_head: yes
use_internal_ips: true

shared_mounts:
    - path: /mnt/galaxy
      src: pulsar-nci-test:/mnt/galaxy
      fstype: nfs
      state: mounted
    - path: /mnt/pulsar
      src: pulsar-nci-test:/mnt/pulsar
      fstype: nfs
      state: mounted


# cvmfs
cvmfs_cache_base: /mnt/var/lib/cvmfs