---
- block:
    - name: Make the script directory
      file:
        state: directory
        path: "{{ clean_tmpdisk_script_dir }}"
    - name: Template variables
      template:
        src: clean_tmpdisk_variables.yml.j2
        dest: "{{ clean_tmpdisk_script_dir }}/clean_tmpdisk_variables.yml"
    - name: Copy script
      copy:
        src: clean_tmpdisk.py
        dest: "{{ clean_tmpdisk_script_dir }}/clean_tmpdisk.py"
    - cron:
        name: clean_tmpdisk
        hour: "{{ clean_tmpdisk_cron_hour }}"
        minute: "{{ clean_tmpdisk_cron_minute }}"
        job: "python {{ clean_tmpdisk_script_dir }}/clean_tmpdisk.py"
        disabled: "{{ not clean_tmpdisk_enable_cron_job }}"  # set clean_tmpdisk_enable_cron_job to false at first
  become: true
  become_user: "{{ clean_tmpdisk_user }}"
