slurm_roles: ['exec']

add_hosts_head: yes

clean_tmpdisk_tmp_dir: /tmp  # no mounted tmpdisk

shared_mounts:
    - path: /mnt/custom-indices
      src: pulsar-paw:/mnt/custom-indices
      fstype: nfs
      state: mounted
    - path: /mnt/pulsar
      src: pulsar-paw:/mnt/pulsar
      fstype: nfs
      state: mounted
    - path: /mnt/tools-indices
      src: pulsar-paw:/mnt/tools-indices
      fstype: nfs
      state: absent

