---

- name: Set ip_field fact
  set_fact:
    ip_field: "{{ use_internal_ips|d(false) | ternary('internal_ip', 'ansible_ssh_host') }}"

- name: Add IPs to hosts
  block:
    - name: "Add {{ ip_field }} to {{ hosts_filename }} for slurm head node"
      lineinfile:
          path: "{{ hosts_filename }}"
          regexp: "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+\t{{ item }}$"
          line: "{{ hostvars[item][ip_field] }}\t{{ item }}"
          state: present
          backup: yes
      when: add_hosts_head|d(false)
      with_items:
          "{{ head_nodes|d([]) }}"
    
    - name: "Add {{ ip_field }} to {{ hosts_filename }} for handlers node"
      lineinfile:
          path: "{{ hosts_filename }}"
          regexp: "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+\t{{ item }}$"
          line: "{{ hostvars[item][ip_field] }}\t{{ item }}"
          state: present
          backup: yes
      when: add_hosts_handlers|d(false)
      with_items:
          "{{ handlers_nodes|d([]) }}"

    - name: "Add {{ ip_field }} to {{ hosts_filename }} for worker nodes"
      lineinfile:
          path: "{{ hosts_filename }}"
          regexp: "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+\t{{ item }}$"
          line: "{{ hostvars[item][ip_field] }}\t{{ item }}"
          state: present
          backup: yes
      when: add_hosts_workers|d(false)
      with_items:
          "{{ worker_nodes|d([]) }}"

    - name: "Add {{ ip_field }} to {{ hosts_filename }} for Galaxy server"
      lineinfile:
          path: "{{ hosts_filename }}"
          regexp: "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+\t{{ item }}$"
          line: "{{ hostvars[item][ip_field] }}\t{{ item }}"
          state: present
          backup: yes
      when: add_hosts_galaxy|d(false)
      with_items:
          "{{ galaxy_nodes|d([]) }}"
