

# Host specific Rabbit settings
rabbitmq_users:
  - user: admin
    password: "{{ rabbitmq_password_admin }}"
    tags: administrator
    vhost: /
  - user: telegraf
    password: "{{ rabbitmq_password_telegraf }}"
    tags: administrator
    vhost: /
  - user: galaxy
    password: "{{ rabbitmq_password_galaxy }}"
    vhost: galaxy
  - user: galaxy_au
    password: "{{ rabbitmq_password_galaxy_au }}"
    vhost: /pulsar/galaxy_au
  - user: galaxy_nci_test
    password: "{{ rabbitmq_password_galaxy_nci_test }}"
    vhost: /pulsar/galaxy_nci_test
  - user: galaxy_eu_gpu
    password: "{{ rabbitmq_password_galaxy_eu_gpu }}"
    vhost:  /pulsar/galaxy_eu_gpu
  - user: galaxy_azure_0
    password: "{{ rabbitmq_password_galaxy_azure_0 }}"
    vhost: /pulsar/galaxy_azure_0
  - user: galaxy_reservation_g2_xlarge_A
    password: "{{ rabbitmq_password_galaxy_reservation_g2_xlarge_A }}"
    vhost: /pulsar/galaxy_reservation_g2_xlarge_A
  - user: galaxy_reservation_g2_xlarge_B
    password: "{{ rabbitmq_password_galaxy_reservation_g2_xlarge_B }}"
    vhost: /pulsar/galaxy_reservation_g2_xlarge_B
  - user: galaxy_qldgpu_dev
    password: "{{ rabbitmq_password_galaxy_qldgpu_dev }}"
    vhost: /pulsar/galaxy_qldgpu_dev
  - user: galaxy_queues
    password: "{{ rabbitmq_password_galaxy }}"
    vhost: /galaxy/galaxy_queues
  - user: flower
    password: "{{ rabbitmq_password_galaxy }}"
    vhost: /galaxy/galaxy_queues
    tags: administrator

rabbitmq_vhosts:
  - galaxy
  - /pulsar/galaxy_au
  - /pulsar/galaxy_nci_test
  - /pulsar/galaxy_eu_gpu
  - /pulsar/galaxy_azure_0
  - /pulsar/galaxy_reservation_g2_xlarge_A
  - /pulsar/galaxy_reservation_g2_xlarge_B
  - /pulsar/galaxy_qldgpu_dev
  - /galaxy/galaxy_queues

rabbitmq_version: 3.10.5-1

rabbitmq_password_admin: "{{ vault_rabbitmq_password_admin_dev }}"
rabbitmq_password_telegraf: "{{ vault_rabbitmq_password_telegraf_dev }}"
rabbitmq_password_galaxy: "{{ vault_rabbitmq_password_galaxy_dev }}"
rabbitmq_password_galaxy_au: "{{ vault_rabbitmq_password_galaxy_au_dev }}"
rabbitmq_password_galaxy_nci_test: "{{ vault_rabbitmq_password_galaxy_nci_test }}"
rabbitmq_password_galaxy_eu_gpu: "{{ vault_rabbitmq_password_galaxy_eu_gpu }}"
rabbitmq_password_galaxy_azure_0: "{{ vault_rabbitmq_password_galaxy_azure_0 }}"
rabbitmq_password_galaxy_reservation_g2_xlarge_A: "{{ vault_rabbitmq_password_galaxy_reservation_g2_xlarge_A }}"
rabbitmq_password_galaxy_reservation_g2_xlarge_B: "{{ vault_rabbitmq_password_galaxy_reservation_g2_xlarge_B }}"
rabbitmq_password_galaxy_qldgpu_dev: "{{ vault_rabbitmq_password_galaxy_qldgpu_dev }}"

# Host specific Slurm settings
slurm_roles: ['controller', 'dbd']

add_hosts_workers: yes
add_hosts_handlers: yes
add_hosts_galaxy: yes

#Mariadb
mariadb_password_slurm: "{{ vault_mariadb_password_slurm }}"
mariadb_password_root: "{{ vault_mariadb_password_root }}"
