hostname: "{{ ansible_hostname }}.genome.edu.au"


# Jenkins settings
jenkins_hostname: jenkins-2024.genome.edu.au
jenkins_http_port: 8080
jenkins_admin_username: admin
jenkins_admin_password: "{{ vault_jenkins_2024_admin_password }}"
jenkins_package_state: latest
jenkins_plugins:
  - build-timeout
  - git
  - github
  - htmlpublisher
  - matrix-auth
  - slack
  - ssh-agent
  - sshd
jenkins_plugins_install_dependencies: true


# Keys and shares
create_ssh_key: yes  # Only the first time.
ssl_country: "AU"
ssl_state: "Vic"
ssl_location: "Melbourne"
ssl_organisation: "Galaxy Australia"
ssl_operational_unit: "Jenkins 2024"
ssl_email: "help@genome.edu.au"


# Certbot
certbot_auto_renew_hour: "{{ 23 |random(seed=inventory_hostname)  }}"
certbot_auto_renew_minute: "{{ 59 |random(seed=inventory_hostname)  }}"
certbot_auth_method: --webroot
certbot_install_method: virtualenv
certbot_auto_renew: yes
certbot_auto_renew_user: root
certbot_environment: production
certbot_well_known_root: /srv/nginx/_well-known_root
certbot_share_key_users:
  - nginx
certbot_post_renewal: |
    systemctl restart nginx || true
certbot_domains:
  - "{{ hostname }}"
certbot_agree_tos: --agree-tos


# NGINX
nginx_selinux_allow_local_connections: true
nginx_servers:
  - redirect-ssl
nginx_enable_default_server: false
nginx_ssl_servers:
  - jenkins-2024
nginx_conf_http:
  client_max_body_size: 1g
nginx_remove_default_vhost: true
nginx_ssl_role: usegalaxy_eu.certbot
nginx_conf_ssl_certificate: /etc/ssl/certs/fullchain.pem
nginx_conf_ssl_certificate_key: /etc/ssl/user/privkey-nginx.pem

