# Specific settings for galaxy dev application/web server

galaxy_db_user_password: "{{ vault_pawsey_db_user_password }}"

# ansible-galaxy
galaxy_dynamic_job_rules_src_dir: files/galaxy/dynamic_job_rules/pawsey
galaxy_dynamic_job_rules_dir: "{{ galaxy_root }}/dynamic_job_rules"
galaxy_dynamic_job_rules:
  - dynamic_rules/destination_mapper.py
  - dynamic_rules/tool_destinations.yml
  - readme.txt

galaxy_tools_indices_dir: /mnt/tools-indices      ########## check this
galaxy_tmp_dir: /mnt/tmp      ########## check this

__galaxy_config:
  galaxy:
    admin_users: "{{ machine_users | selectattr('email', 'defined') | map(attribute='email') | join(',') }}" # everyone is an admin on pawsey
    brand: "Australia"
    database_connection: "postgres://galaxy:{{ vault_pawsey_db_user_password }}@pawsey-db.usegalaxy.org.au:5432/galaxy"
    id_secret: "{{ vault_pawsey_id_secret }}"
    file_path: /mnt/user-data      ########## check this

# variables for attaching mounted volume to application server
galaxyserver_attached_volume_device: /dev/vdc
galaxyserver_attached_volume_path: /mnt
galaxyserver_attached_volume_fstype: ext4


#Galaxy Job Conf
galaxy_jobconf:
    plugin_workers: 4
    handlers:
        count: "{{ galaxy_handler_count }}"
    plugins:
      - id: local
        load: galaxy.jobs.runners.local:LocalJobRunner
        workers: 4
      - id: dynamic
        params:
          rules_module: dynamic_rules
      - id: slurm
        load: galaxy.jobs.runners.slurm:SlurmJobRunner
    default_destination: gateway
    destinations:
      - id: local
        runner: local
      - id: gateway
        runner: dynamic
        params:
            type: python
            function: gateway
      - id: dynamic_dtd
        runner: dynamic
        params:
          type: dtd
      - id: slurm_dest
        runner: slurm
        params:
            nativeSpecification: "--nodes=1 --ntasks=2 --ntasks-per-node=2 --mem=7760"
    limits:
      #General limits for user submission
      - type: anonymous_user_concurrent_jobs
        value: 1
      - type: registered_user_concurrent_jobs
        value: 10


# cvmfs
cvmfs_cache_base: /mnt/var/lib/cvmfs  ########### check this