

# Host specific Rabbit settings
rabbitmq_users:
  - user: admin
    password: "{{ rabbitmq_password_admin }}"
    tags: administrator
    vhost: /
  - user: telegraf
    password: "{{ rabbitmq_password_telegraf }}"
    tags: administrator
    vhost: /
  - user: galaxy
    password: "{{ rabbitmq_password_galaxy }}"
    vhost: galaxy
  - user: galaxy_mel2
    password: "{{ rabbitmq_password_galaxy_mel2 }}"
    vhost: /pulsar/galaxy_mel2
  - user: galaxy_mel3
    password: "{{ rabbitmq_password_galaxy_mel3 }}"
    vhost: /pulsar/galaxy_mel3
  - user: galaxy_paw
    password: "{{ rabbitmq_password_galaxy_paw }}"
    vhost: /pulsar/galaxy_paw
    
rabbitmq_vhosts:
  - galaxy
  - /pulsar/galaxy_mel2
  - /pulsar/galaxy_mel3
  - /pulsar/galaxy_paw

rabbitmq_password_admin: "{{ vault_rabbitmq_password_admin_prod }}"
rabbitmq_password_telegraf: "{{ vault_rabbitmq_password_telegraf_prod }}"
rabbitmq_password_galaxy: "{{ vault_rabbitmq_password_galaxy_prod }}"
rabbitmq_password_galaxy_mel2: "{{ vault_rabbitmq_password_galaxy_mel2_prod }}"
rabbitmq_password_galaxy_mel3: "{{ vault_rabbitmq_password_galaxy_mel3_prod }}"
rabbitmq_password_galaxy_paw: "{{ vault_rabbitmq_password_galaxy_paw_prod }}"

