

# Host specific Rabbit settings
rabbitmq_users:
  - user: admin
    password: "{{ rabbitmq_password_admin }}"
    tags: administrator
    vhost: /
  - user: telegraf
    password: "{{ rabbitmq_password_telegraf }}"
    tags: administrator
    vhost: /
  - user: galaxy
    password: "{{ rabbitmq_password_galaxy }}"
    vhost: galaxy
  - user: galaxy_au
    password: "{{ rabbitmq_password_galaxy_au }}"
    vhost: /pulsar/galaxy_au

rabbitmq_vhosts:
  - galaxy
  - /pulsar/galaxy_au

rabbitmq_version: 3.10.6-1

rabbitmq_password_admin: "{{ vault_rabbitmq_password_admin_staging }}"
rabbitmq_password_telegraf: "{{ vault_rabbitmq_password_telegraf_staging }}"
rabbitmq_password_galaxy: "{{ vault_rabbitmq_password_galaxy_staging }}"
rabbitmq_password_galaxy_au: "{{ vault_rabbitmq_password_galaxy_au_staging }}"

# Host specific Slurm settings
slurm_roles: ['controller', 'dbd']

add_hosts_workers: yes

#Mariadb
mariadb_password_slurm: "{{ vault_staging_mariadb_password_slurm }}"
mariadb_password_root: "{{ vault_staging_mariadb_password_root }}"
