---
  - name: Add env vars for gxadmin to machine_users .bashrc files
    lineinfile:
      path: "/home/{{ username }}/.bashrc"
      line: "export {{ obj.var }}='{{ obj.val }}'"
    loop:
      - var: PGHOST
        val: "{{ db_address }}"
      - var: PGUSER
        val: "{{ 'reader' if not username == 'ubuntu' else 'galaxy' }}"
      - var: PGDATABASE
        val: "galaxy"
      - var: PGPORT
        val: "5432"
      - var: GALAXY_CONFIG_DIR
        val: "{{ galaxy_config_dir }}"
      - var: GALAXY_MUTABLE_CONFIG_DIR
        val: "{{ galaxy_mutable_config_dir }}"
      - var: GALAXY_ROOT
        val: "{{ galaxy_server_dir }}"
      - var: GALAXY_CONFIG_FILE
        val: "{{ galaxy_config_dir }}/galaxy.yml"
    loop_control:
      loop_var: obj
