slurm_roles: ['exec']

add_hosts_head: yes

shared_mounts:
    - path: /mnt/tools-indices
      src: pulsar-mel2:/mnt/tools-indices
      fstype: nfs
      state: mounted
    - path: /mnt/pulsar
      src: pulsar-mel2:/mnt/pulsar
      fstype: nfs
      state: mounted
    - path: /mnt/galaxy
      src: pulsar-mel2:/mnt/galaxy
      fstype: nfs
      state: absent


# cvmfs
cvmfs_cache_base: /mnt/var/lib/cvmfs
cvmfs_quota_limit: 20000

#Attached volume
attached_volumes:
  - device: /dev/vdb
    path: /mnt
    fstype: ext4